In [19]:
import numpy as np

nx = 3
ny = 3
nz = 3

f2 = np.zeros((nx, ny))
f3 = np.zeros((nx, ny, nz))

n = 0
m = 0
print(f2.shape)

for i in range(nx):
    for j in range(ny):
        n = n + 1
        f2[i, j] = n
        for k in range(nz):
            m = m + 1
            f3[i, j, k] = m

print('f2 = \n', f2)
print('f2.shape = \n', f2.reshape((f2.shape[0] * f2.shape[1])) )
print('f2[2, 1] = ', f2[2, 1])

print('f3 = \n', f3)
print('f3.shape = \n', f3.reshape((f3.shape[0] * f3.shape[1] * f3.shape[2],)) )

(3, 3)
f2 = 
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
f2.shape = 
 [1. 2. 3. 4. 5. 6. 7. 8. 9.]
f2[2, 1] =  8.0
f3 = 
 [[[ 1.  2.  3.]
  [ 4.  5.  6.]
  [ 7.  8.  9.]]

 [[10. 11. 12.]
  [13. 14. 15.]
  [16. 17. 18.]]

 [[19. 20. 21.]
  [22. 23. 24.]
  [25. 26. 27.]]]
f3.shape = 
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27.]


In [20]:
f = [1, 2, 3]
a, s, d = f

In [24]:
g = {'a' : [1, 2, 3, 4], 'b' : np.zeros((2, 3))}
np.save('test.npy', g)
h = np.load('test.npy')
q, w, e, r = h.item().get('a')

In [25]:
q

1

In [30]:
g = [1, 2, lambda x: x**2, 4]
list(tuple(g))


[1, 2, <function __main__.<lambda>(x)>, 4]

In [5]:
g = [0, 1, 2, 3, 4, 5]
mu = 3
nu = len(g)
g[mu//2:nu-mu//2-mu%2]

[1, 2, 3]