In [39]:
import numpy as np

nx = 3
ny = 3
nz = 3

f2 = np.zeros((nx, ny))
f3 = np.zeros((nx, ny, nz))

n = 0
m = 0
print(f2.shape)

for i in range(nx):
    for j in range(ny):
        n = n + 1
        f2[i, j] = n
        for k in range(nz):
            m = m + 1
            f3[i, j, k] = m

print('f2 = \n', f2)
print('f2.shape = \n', f2.reshape((f2.shape[0] * f2.shape[1])) )
print('f2[2, 1] = ', f2[2, 1])

print('f3 = \n', f3)
print('f3.shape = \n', f3.reshape((f3.shape[0] * f3.shape[1] * f3.shape[2],)) )

(3, 3)
f2 = 
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
f2.shape = 
 [1. 2. 3. 4. 5. 6. 7. 8. 9.]
f2[2, 1] =  8.0
f3 = 
 [[[ 1.  2.  3.]
  [ 4.  5.  6.]
  [ 7.  8.  9.]]

 [[10. 11. 12.]
  [13. 14. 15.]
  [16. 17. 18.]]

 [[19. 20. 21.]
  [22. 23. 24.]
  [25. 26. 27.]]]
f3.shape = 
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27.]


In [40]:
f = [1, 2, 3]
a, s, d = f

In [41]:
g = {'a' : [1, 2, 3, 4], 'b' : np.zeros((2, 3))}
np.save('test.npy', g)
h = np.load('test.npy')
q, w, e, r = h.item().get('a')

In [42]:
g = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
f = np.array([1, 2, 3, 4])
rng_state = np.random.get_state()
np.random.shuffle(g)
np.random.set_state(rng_state)
np.random.shuffle(f)
print(g)
print(f)

[[7 8]
 [5 6]
 [3 4]
 [1 2]]
[4 3 2 1]


In [43]:
np.str(3)

'3'

In [44]:
l = [1, 2 ,3, 4]
sum(l)/len(l)

2.5

In [45]:
import numpy as np
g = np.linspace(1, 2, 3)
g.size

3

In [46]:
np.zeros((1, 2))
g = np.array()
f = np.array([[5, 5, 4], [3, 2, 1]])
np.append(f, g, axis=0)

TypeError: array() missing required argument 'object' (pos 1)

In [1]:
import numpy as np
x = np.ones((2, 3, 4))
y = np.array([[1, 2, 3],[4, 5, 6]]) # 2*3
yf = np.tile(y.transpose(), (4, 1, 1)).transpose()
print(yf.shape)
print(yf)

(2, 3, 4)
[[[1 1 1 1]
  [2 2 2 2]
  [3 3 3 3]]

 [[4 4 4 4]
  [5 5 5 5]
  [6 6 6 6]]]


In [9]:
#rem_feature_idx = range(10)
null_feature_idx = {0, 1, 2, 5, 6, 7, 8}
rem_feature_idx = [i for i in rem_feature_idx if i not in set(null_feature_idx)]
print(rem_feature_idx)


[3, 4, 9]


In [12]:
f = {'r':4, 'g':6}
g = f
f = {'r':{'t':4, 'e':6}, 'g':6}
h = {'r':{'e':6, 't':4}, 'g':6}
f==h

True

24

In [31]:
metadata = {'a':{'g': 1, 'h': 2}, 'b':{'t':4, 'y':6}}
g = [key for val0 in metadata.values() for key in val0.keys()]
g

['g', 'h', 't', 'y']

In [32]:
g = 1
if g==2:
    print(g)
elif g == 3:
    print(g)

In [33]:
set(None)

TypeError: 'NoneType' object is not iterable